//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoHiking.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripActivity()
        {
            this.GroupImages = new HashSet<GroupImage>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int activity_id { get; set; }
        public string group_name { get; set; }
        public System.DateTime activity_date { get; set; }
        public string meeting_time { get; set; }
        public string meeting_location { get; set; }
        public string custom_schedule { get; set; }
        public string leader_message { get; set; }
        public Nullable<int> max_participants { get; set; }
        public int price { get; set; }
        public int mt_id { get; set; }
        public string mt_name { get; set; }
        public string badge { get; set; }
        public int walk_days { get; set; }
        public string location { get; set; }
        public int diff { get; set; }
        public decimal dist_km { get; set; }
        public int time_min { get; set; }
        public int ascend_m { get; set; }
        public int descend_m { get; set; }
        public string trail_cond { get; set; }
        public string route_type { get; set; }
        public int min_alt_m { get; set; }
        public int max_alt_m { get; set; }
        public string mt_range { get; set; }
        public byte park_permit { get; set; }
        public byte mt_permit { get; set; }
        public string TripDetails { get; set; }
        public string region { get; set; }
        public string TripSchedule { get; set; }
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string status { get; set; }
        public Nullable<int> current_participants { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string team_name { get; set; }
        public string FeeIncludes { get; set; }
        public int participants { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupImage> GroupImages { get; set; }
        public virtual MountainTrail MountainTrail { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
