//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoHiking.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int ProfileId { get; set; }
        public int UserId { get; set; }
        public string RealName { get; set; }
        public bool Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Nationality { get; set; }
        public string IdNumber { get; set; }
        public string LineId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhone { get; set; }
        public bool HasCompanion { get; set; }
        public string CompanionName { get; set; }
        public string HikingExperience { get; set; }
        public string ExerciseHabit { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> activity_id { get; set; }
        public Nullable<bool> is_creator { get; set; }
    
        public virtual TripActivity TripActivity { get; set; }
        public virtual User User { get; set; }
    }
}
